Ability for RDFS to run on a multi-node ZK quorum
Rice-Comp413-2016/RDFS pull request #102
Opened 2016-12-07 04:10 UTC by Vegetable26

Not very high quality code :( 
Uses polling and has an occasional memory leak if zookeeper drops connection. But it works hopefully :)

2016-12-07 04:12 UTC, Vegetable26 commented
The consistency guarantees are basically that any file metadata is instantly synced before we acknowledge the HDFS client.

On the other all block locations and DN information is lazily read. Basically, we do not sync until we read a block_locations and find 0 available DNs. This guarantees that by the time the client calls complete() each block_location has at least one DN, assuming none died. Performance went from ~7 seconds to 8-9 seconds now.

2016-12-07 04:39 UTC, nichhk requested changes

2016-12-07 04:39 UTC, nichhk commented on zkwrapper/source/zkwrapper.cc
> +		while (!root_exists) {
Why do we need this while loop?

2016-12-07 04:39 UTC, nichhk commented on zkwrapper/source/zkwrapper.cc
> +			std::this_thread::sleep_for (std::chrono::milliseconds(1000));
I would just set the value to true and not do anything else in this lambda.

2016-12-07 04:39 UTC, nichhk commented on zkwrapper/source/zkwrapper.cc
> +		while (!(* flag) && count < 2000) {
Having the thread sleep for 1ms 2000 times is not necessarily 2s, I think. 
I think we can make the thread sleep for 2s and then just return flag.

2016-12-07 04:39 UTC, nichhk commented on zkwrapper/source/zkwrapper.cc
> +		int rc = zoo_async(zh, full_path.c_str(), completion, flag);
we should return if rc is no good

2016-12-07 04:43 UTC, Vegetable26 commented on zkwrapper/source/zkwrapper.cc
> +		while (!(* flag) && count < 2000) {
This would guarantee that the function would block for 2 seconds though. Polling is to see if it returned earlier than 2 seconds

2016-12-07 04:44 UTC, Vegetable26 commented on zkwrapper/source/zkwrapper.cc
> +		while (!root_exists) {
This is sketchy but basically with multiple ZNodes or real environments, often times the initialization can fail for a number of times, before we get connected to ZK. Thus this is basically a blocking method waiting on a valid connection to ZK before allowing the ZK_client to be constructed.

2016-12-07 04:46 UTC, Vegetable26 commented on zkwrapper/source/zkwrapper.cc
> +		int rc = zoo_async(zh, full_path.c_str(), completion, flag);
Resolved

2016-12-07 04:47 UTC, Vegetable26 commented on zkwrapper/source/zkwrapper.cc
> +			std::this_thread::sleep_for (std::chrono::milliseconds(1000));
This is a minimal effort at preventing the memory leak. I sleep before delete in hope that the blocked function awakes and exits before we attempt to free this flag. This is very ugly, but basically I am not sure if there are any super good ways to guarantee that we do not free this variable before the blocking function attempts to read it

2016-12-07 04:50 UTC, nichhk commented on zkwrapper/source/zkwrapper.cc
> +			std::this_thread::sleep_for (std::chrono::milliseconds(1000));
Can we not just free flag at the end of the flush method?

2016-12-07 04:52 UTC, nichhk commented on zkwrapper/source/zkwrapper.cc
> +		while (!(* flag) && count < 2000) {
Good point.

2016-12-07 05:12 UTC, Vegetable26 commented on zkwrapper/source/zkwrapper.cc
> +			std::this_thread::sleep_for (std::chrono::milliseconds(1000));
Well sometimes the call_back never returns. And sometimes it returns after 10 seconds and then a double free occurs leading to a SegFault

2016-12-07 19:14 UTC, Swyrough commented on zkwrapper/source/zkwrapper.cc
> +			std::this_thread::sleep_for (std::chrono::milliseconds(1000));
lol

2016-12-07 19:14 UTC, Swyrough commented on zkwrapper/source/zkwrapper.cc
> +			std::this_thread::sleep_for (std::chrono::milliseconds(1000));
brutal!

2016-12-07 19:16 UTC, Swyrough approved these changes

2016-12-07 19:16 UTC, Swyrough commented on test/integration/ReplicationTest.cc
> +        ASSERT_EQ(0, system("diff expected_testfile1234 actual_testfile1234 > /dev/null"));
why?

2016-12-07 19:16 UTC, Swyrough commented on test/integration/ReplicationTest.cc
> +        sleep(30);
oh yeaaaaa

2016-12-08 19:48 UTC, Vegetable26 commented
Can I merge this?

2016-12-08 19:51 UTC, merged