Updated rename_file method in zk_nn_client to use multiop and added test
Rice-Comp413-2016/RDFS pull request #48
Opened 2016-11-09 05:01 UTC by prb2

Passes test case and was able to do copyFromLocal and cat.

Can @pelmers and/or @nichhk code review this?

2016-11-09 17:58 UTC, nichhk requested changes
Looks good to me. Just some small things~~~

2016-11-09 17:58 UTC, nichhk commented on zookeeper/source/zk_nn_client.cc
Why doesn't this function take error_code as a param?

2016-11-09 17:58 UTC, nichhk commented on zookeeper/source/zk_nn_client.cc
>  		std::string src_znode = "/fileSystem" + src;
please use ZooKeeperPath()

2016-11-09 17:58 UTC, nichhk commented on test/namenode/NameNodeTest.cc
> +
Can you put some asserts to make sure that old_name doesn't exist anymore?

2016-11-09 17:58 UTC, nichhk commented on zookeeper/source/zk_nn_client.cc
> +		id->set_hostname("localhost"); // TODO: Fill out with the proper value
Do you know what this TODO is?

2016-11-09 21:11 UTC, prb2 commented on test/namenode/NameNodeTest.cc
> +
Done.

2016-11-09 21:11 UTC, prb2 commented on zookeeper/source/zk_nn_client.cc
> +		id->set_hostname("localhost"); // TODO: Fill out with the proper value
No idea...not sure who wrote this.

2016-11-09 21:11 UTC, prb2 commented on zookeeper/source/zk_nn_client.cc
>  		std::string src_znode = "/fileSystem" + src;
Done.

d7aabdd3727499bfe042bde05de9d9b9a5a7d041

2016-11-11 02:01 UTC, prb2 commented on zookeeper/source/zk_nn_client.cc
As we discussed, it now prints out errors when something in multiop fails.

2e990fc

2016-11-11 02:01 UTC, prb2 commented
@nichhk Ready to merge?

2016-11-11 17:49 UTC, merged