Add prevblockcomplete function
Rice-Comp413-2016/RDFS pull request #53
Opened 2016-11-13 03:50 UTC by Joe--Chen

Exception branch has to be merged to get this function to work (in develop branch there is no exception handling).

2016-11-13 05:13 UTC, nichhk requested changes

2016-11-13 05:13 UTC, nichhk commented on zookeeper/source/zk_nn_client.cc
> +		if (zk->get_children("/block_locations/" + block_id_str, children, error_code)) {
Please use the constant BLOCK_LOCATIONS.

2016-11-13 05:13 UTC, nichhk commented on zookeeper/source/zk_nn_client.cc
> +			if (children.size() >= 1){
We should be reading MIN_REPLICATION from a config, but for now, can you just make a constant instead of using 1?

2016-11-13 05:13 UTC, nichhk commented on zkwrapper/source/zkwrapper.cc
> +    children.resize(stvector.count);
Why? children should be dynamically resized as elements are pushed back.

2016-11-13 05:24 UTC, Joe--Chen commented on zookeeper/source/zk_nn_client.cc
> +			if (children.size() >= 1){
Three issues addressed and code updated.

2016-11-13 18:52 UTC, nichhk commented
Sorry I forgot to mention this... can you add tests on addBlock? One that works if the previousBlockComplete; one that fails otherwise.

2016-11-14 16:22 UTC, Joe--Chen commented
Test case added.

2016-11-14 21:06 UTC, nichhk commented on test/namenode/NameNodeTest.cc
> +		ASSERT_EQ(false, client->previousBlockComplete(block_id));
previousBlockComplete should not be a public method. So, we should only be able to test it through addBlock. Other people might have a different opinion about this, though.

2016-11-15 00:44 UTC, nichhk approved these changes

2016-11-15 00:44 UTC, nichhk commented
LGTM. Remember that we need to add a call to prevBlockComplete when we close the file.

2016-11-17 01:41 UTC, nichhk commented
We're gonna merge this in once @efrederic confirms that the periodic task runner works ok.

2016-11-17 02:42 UTC, efrederic commented on test/namenode/NameNodeTest.cc
> +		ASSERT_EQ(false, client->previousBlockComplete(block_id));
There is no previousBlockComplete on this branch so this test does not compile

2016-11-17 02:44 UTC, efrederic commented
I can confirm that the periodic test runner is working. This branch doesn't build currently though because previousBlockComplete does not exist

2016-11-17 04:09 UTC, closed without merging