Data persistence
Rice-Comp413-2016/RDFS pull request #63
Opened 2016-11-14 21:36 UTC by jfking

2016-11-15 02:13 UTC, pelmers commented
@Vegetable26 It looks like your changes in 2345321 use spaces rather than tabs.

2016-11-15 17:39 UTC, pelmers commented
some bookkeeping, this will fix #46.

2016-11-16 22:30 UTC, efrederic commented on native-filesystem/include/native_filesystem.h
> +		long getTotalSpace();
can we make these return uint64_t?

2016-11-16 22:54 UTC, efrederic commented on native-filesystem/source/native_filesystem.cc
> +            }
spacing got a bit out of whack here

2016-11-17 01:37 UTC, nichhk commented on native-filesystem/include/native_filesystem.h
>  		bool writeBlock(uint64_t, std::string);
string ref

2016-11-17 01:39 UTC, nichhk requested changes

2016-11-17 01:39 UTC, nichhk commented on native-filesystem/include/native_filesystem.h
>  		std::string getBlock(uint64_t, bool&);
strange that this returns a string when the rest return a bool

2016-11-17 02:12 UTC, nichhk approved these changes

2016-11-17 02:35 UTC, merged