blockDeleted
Rice-Comp413-2016/RDFS pull request #67
Opened 2016-11-15 01:49 UTC by captain695

2016-11-15 02:03 UTC, pelmers commented on zookeeper/source/zk_client_common.cc
> +    const std::string ZkClientCommon::DELETE_BACKSLASH = "/delete/";
🙃

2016-11-15 02:07 UTC, captain695 commented on zookeeper/source/zk_client_common.cc
> +    const std::string ZkClientCommon::DELETE_BACKSLASH = "/delete/";
Oops yeah I'll delete that

2016-11-15 02:08 UTC, pelmers commented on zookeeper/source/zk_client_common.cc
> +    const std::string ZkClientCommon::DELETE_BACKSLASH = "/delete/";
oh that was not any review, just noting for amusement that we say backslash for /

2016-11-15 02:09 UTC, pelmers commented on zookeeper/source/zk_client_common.cc
> +    const std::string ZkClientCommon::DELETE_BACKSLASH = "/delete/";
although now that you mention it i think it's right to delete it since it's never used

2016-11-15 19:51 UTC, Vegetable26 commented on test/zookeeper/zk_dn_client_test.cc
> -TEST_F(ZKDNClientTest, RegisterMakesWorkQueues){
Just curious, why are we removing this test?

2016-11-15 19:53 UTC, Vegetable26 commented on zookeeper/include/zk_dn_client.h
> +    bool blockDeleted(uint64_t uuid, uint64_t size_bytes);
I don't think size_bytes is ever used

2016-11-15 19:54 UTC, Vegetable26 commented on zookeeper/source/zk_dn_client.cc
> +		if (zk->exists(BLOCK_LOCATIONS + std::to_string(uuid), exists, error_code)) {
Can we fold these two deletes into a multi-op?

2016-11-15 19:56 UTC, Vegetable26 commented on zookeeper/source/zk_dn_client.cc
> +		if (zk->exists(BLOCK_LOCATIONS + std::to_string(uuid), exists, error_code)) {
In the future, we will also want to delete the corresponding work_queue/delete/<datanode_id>/<block_id> znode in this multi-op

2016-11-16 00:58 UTC, captain695 commented on test/zookeeper/zk_dn_client_test.cc
> -TEST_F(ZKDNClientTest, RegisterMakesWorkQueues){
I accidentally left it out when merging the two commits. Will add back in

2016-11-16 01:01 UTC, captain695 commented on zookeeper/include/zk_dn_client.h
> +    bool blockDeleted(uint64_t uuid, uint64_t size_bytes);
You are correct. Removed

2016-11-16 01:02 UTC, captain695 commented on zookeeper/source/zk_dn_client.cc
> +		if (zk->exists(BLOCK_LOCATIONS + std::to_string(uuid), exists, error_code)) {
I asked @nichhk and @cburk and they thought no, but if anyone has a reason for thinking we should chime in

2016-11-16 01:42 UTC, captain695 commented
@nichhk does this all look good?

2016-11-16 03:09 UTC, nichhk requested changes

2016-11-16 03:09 UTC, nichhk commented on zookeeper/source/zk_dn_client.cc
> +		if (zk->exists(BLOCK_LOCATIONS + std::to_string(uuid), exists, error_code)) {
The exists path and delete path don't match.

2016-11-16 03:09 UTC, nichhk commented on zookeeper/source/zk_dn_client.cc
> +		if (zk->exists(HEALTH_BACKSLASH + id + BLOCKS, exists, error_code)) {
The exists path and delete path don't match.

2016-11-16 04:01 UTC, efrederic commented on test/zookeeper/zk_dn_client_test.cc
> +    std::string path = "/work_queues/replicate/" + dn_id;
spacing

2016-11-16 04:14 UTC, Vegetable26 commented on zookeeper/source/zk_dn_client.cc
> +		if (zk->exists(BLOCK_LOCATIONS + std::to_string(uuid), exists, error_code)) {
Oh kk, sounds good :) I think multi-ops might still be a good idea though

2016-11-16 22:19 UTC, nichhk approved these changes

2016-11-17 05:33 UTC, merged