Queue pop actually stores the popped data; created test for this as well
Rice-Comp413-2016/RDFS pull request #72
Opened 2016-11-16 06:27 UTC by prb2

2016-11-16 21:51 UTC, prb2 commented
I think this PR is ready for merge. 

1. Fixed the bug in the pop method where the popped node's data wasn't actually being stored and created a test for this in ZKQueueTest.

2. Added locking on the queue when a pop is requested to prevent races when multiple clients attempt to pop from the same queue.

2016-11-16 22:41 UTC, nichhk requested changes

2016-11-16 22:41 UTC, nichhk commented on zkwrapper/source/zk_queue.cc
>  		// TODO: set a custom error code?
I think it would make sense to use ZNONODE error, since there is no node to pop.

2016-11-16 22:41 UTC, nichhk commented on zkwrapper/source/zk_queue.cc
>  	std::string peeked_path = q_path + "/" + children.back();
Why children.back()? Don't we need to sort children and then use children.front()?

2016-11-16 23:01 UTC, nichhk commented
Can you add params to push, pop, and peek that give the path of the corresponding ZNode?

2016-11-17 01:40 UTC, prb2 commented
@nichhk Addressed all of your comments in: 7052df4

2016-11-17 01:45 UTC, nichhk commented on zkwrapper/source/zk_queue.cc
> +		error_code = ZNONODE;
gotta unlock before return

2016-11-17 01:46 UTC, prb2 commented on zkwrapper/source/zk_queue.cc
> +		error_code = ZNONODE;
I do...line 70

2016-11-17 01:48 UTC, prb2 commented on zkwrapper/source/zk_queue.cc
> +		error_code = ZNONODE;
Okay, fixed in: 7052df4

2016-11-17 01:50 UTC, nichhk approved these changes

2016-11-17 01:52 UTC, merged