Namenode ha plugin
Rice-Comp413-2016/RDFS pull request #98
Opened 2016-12-05 06:55 UTC by agardella

@captain695 @cburk

2016-12-05 17:38 UTC, pelmers commented
can you remove the .DS_STORE files?

2016-12-07 02:18 UTC, nichhk commented on rice-namenode/source/main.cc
> -	translator.getRPCServer().serve(io_service);
Why are we able to delete this?

2016-12-07 02:20 UTC, nichhk requested changes
We can have everything start in the ACTIVE state. And transitionToActive and transitionToStandby don't need to do anything.

2016-12-07 02:20 UTC, nichhk commented on rice-namenode/source/HAServiceProtocolImpl.cc
> +HaServiceTranslator::~HaServiceTranslator() {
Destructor is not necessary.

2016-12-07 03:37 UTC, pelmers commented on vagrant_provision.sh
> +cat /home/vagrant/rdfs/config/core-site.xml > /home/vagrant/hadoop/etc/hadoop/core-site.xml
can you remove the lines above this which touch the same files but get overwritten here?
`cat > /home/vagrant/hadoop3/etc/hadoop/core-site.xml <<EOF`
and
`cat > /home/vagrant/hadoop3/etc/hadoop/hdfs-site.xml <<EOF`

2016-12-07 03:37 UTC, pelmers commented on vagrant_provision.sh
> +echo 'python /home/vagrant/rdfs/utility/provision_diff.py' >> /home/vagrant/.bashrc
this line is repeated at the end of the file too, delete this one

2016-12-07 04:01 UTC, Vegetable26 commented
Have we tried the scenario where we have two NameNodes A and B. Kill A, then kill B, then bring back A?

2016-12-07 04:42 UTC, efrederic commented on rice-namenode/include/HaServiceProtocolImpl.h
> +        static const int LEASE_CHECK_TIME; 	// in seconds, how often the namenode checks all leases
is LEASE_CHECK_TIME ever used?

2016-12-07 04:53 UTC, nichhk commented on rice-namenode/include/HaServiceProtocolImpl.h
> +        static const int LEASE_CHECK_TIME; 	// in seconds, how often the namenode checks all leases
Nope leases are gone.

2016-12-07 20:12 UTC, agardella commented on rice-namenode/source/main.cc
> -	translator.getRPCServer().serve(io_service);
Lines 34 and 36 do the same thing

2016-12-07 20:15 UTC, agardella commented on vagrant_provision.sh
> +cat /home/vagrant/rdfs/config/core-site.xml > /home/vagrant/hadoop/etc/hadoop/core-site.xml
I think they're touching different files (the ones in /home/vagrant/hadoop3 as opposed to /home/vagrant/hadoop). It looks like they might be unnecessary anyway, but I'm not totally sure

2016-12-07 21:49 UTC, agardella commented on vagrant_provision.sh
> +echo 'python /home/vagrant/rdfs/utility/provision_diff.py' >> /home/vagrant/.bashrc
fixed

2016-12-07 21:50 UTC, agardella commented on rice-namenode/include/HaServiceProtocolImpl.h
> +        static const int LEASE_CHECK_TIME; 	// in seconds, how often the namenode checks all leases
fixed

2016-12-07 21:50 UTC, agardella commented on rice-namenode/source/HAServiceProtocolImpl.cc
> +HaServiceTranslator::~HaServiceTranslator() {
fixed

2016-12-07 22:34 UTC, pelmers commented on vagrant_provision.sh
> +cat /home/vagrant/rdfs/config/core-site.xml > /home/vagrant/hadoop/etc/hadoop/core-site.xml
they are the same file, `hadoop` is just a link to `hadoop3` because of `ln -s hadoop3 hadoop` a few lines above.

2016-12-08 20:22 UTC, captain695 commented
@Vegetable26 just tried that scenario and it seems to work

2016-12-08 20:36 UTC, captain695 commented
@nichhk does this look all good to merge?

2016-12-08 23:23 UTC, nichhk commented
@captain695 LGTM

2016-12-09 01:46 UTC, captain695 commented
@nichhk I know you guys have been having things break in develop. Should I wait until that's resolved until I try to merge this in?

2016-12-09 20:29 UTC, agardella commented
@nichhk Having all of the namenodes start in active means we can't do a manual failover, and it changes quite a bit of our presentation and demo... it also seems conceptually wrong. What's the reason you wanted that change?

2016-12-10 05:16 UTC, merged